top_stellar/app_notes/urls.py
from django.urls import path, re_path
from app_notes import views
from .models import Notes, Soar, Goals, Tasks
from .filters import NotesFilter, SoarFilter, GoalsFilter, TasksFilter
from django_filters.views import FilterView

app_name = 'app_notes'

urlpatterns = [
	path('', views.HomeListView.as_view(), name='homelist'),
	
	re_path(r'^taglist/(?P<notes_tag>.*)/$', views.HomeTagsListView.as_view(), name="taglist"),
	re_path(r'^genrelist/(?P<notes_genre>.*)/$', views.HomeGenreListView.as_view(), name="genrelist"),

	re_path(r'^staglist/(?P<soar_tag>.*)/$', views.HomeSoarTagsListView.as_view(), name="staglist"),
	re_path(r'^sgenrelist/(?P<soar_genre>.*)/$', views.HomeSoarGenreListView.as_view(), name="sgenrelist"),

	path('search/', views.SearchListView.as_view(), name='searcher'),
	path('ssearch/', views.SoarSearchListView.as_view(), name='ssearcher'),
    path('gsearch/', views.GoalsSearchListView.as_view(), name='gsearcher'),
    path('tsearch/', views.TasksSearchListView.as_view(), name='tsearcher'),
	path('create/', views.NotesCreateView.as_view(), name='creater'),
	path('screate/', views.SoarCreateView.as_view(), name='screater'),
	path('gcreate/', views.GoalsCreateView.as_view(), name='gcreater'),
	path('tcreate/', views.TasksCreateView.as_view(), name='tcreater')
]

top_stellar/pjx_stellar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('markdownx/', include('markdownx.urls')),
    path('', include('app_notes.urls'))
]

if settings.DEBUG == True:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
else:
	print("You've set DEBUG = False, why?")

top_stellar/app_notes/models.py
from django.db import models
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify
from django.utils.text import slugify
from django.utils import timezone
from datetime import datetime

soar_situation_default = 'What problem/task/challenge are you trying to solve?'
soar_obstacles_default = 'What makes this problem/task/challenge difficult?'
soar_actions_default = 'What did you do to solve the problem/task/challenge and what skills did you use?'
soar_results_default = 'What were the results of your actions and how did it impact your program/team?'

class Notes(models.Model):
	title = models.CharField(max_length=100, blank=False)
	genre = models.CharField(max_length=20, blank=True)
	tag = models.CharField(max_length=20, blank=True)
	body = MarkdownxField()
	date = models.DateField(default=timezone.now)
	slug = models.SlugField(max_length=150, unique=True, blank=True)

	def __str__(self):
		return self.title

	def formatted_markdown(self):
		return markdownify(self.body)

	def _get_unique_slug(self):
		slug = slugify(self.title)
		unique_slug = slug
		num = 1
		while Notes.objects.filter(slug=unique_slug).exists():
		    unique_slug = '{}-{}'.format(slug, num)
		    num += 1
		return unique_slug

	def save(self, *args, **kwargs):
		if not self.slug:
		    self.slug = self._get_unique_slug()
		super().save(*args, **kwargs)

	class Meta:
		verbose_name_plural = "Notes"

class Soar(models.Model):
	date = models.DateField(default=timezone.now)
	genre = models.CharField(max_length=20, blank=True)
	tag = models.CharField(max_length=20, blank=True)
	slug = models.SlugField(max_length=150, unique=True, blank=True)
	situation = MarkdownxField(default=soar_situation_default)
	obstacle = MarkdownxField(default=soar_obstacles_default)
	action = MarkdownxField(default=soar_actions_default)
	result = MarkdownxField(default=soar_results_default)

	def __str__(self):
		return self.situation

	def s_formatted_markdown(self):
		return markdownify(self.situation)

	def o_formatted_markdown(self):
		return markdownify(self.obstacle)

	def a_formatted_markdown(self):
		return markdownify(self.action)

	def r_formatted_markdown(self):
		return markdownify(self.result)

	def _get_unique_slug(self):
		slug = slugify(self.situation)
		unique_slug = slug
		num = 1
		while Soar.objects.filter(slug=unique_slug).exists():
			unique_slug = '{}-{}'.format(slug, num)
			num += 1
		return unique_slug

	def save(self, *args, **kwargs):
		if not self.slug:
			self.slug = self._get_unique_slug()
		super().save(*args, **kwargs)


class Goals(models.Model):
	tag = models.CharField(max_length=100, default='goals', blank=False)
	complete = models.BooleanField(default=False, blank=False)
	body = MarkdownxField()
	end_date = models.DateField(default=timezone.now)
	def formatted_markdown(self):
		return markdownify(self.body)
	def time_left(self):
		end = datetime.combine(self.end_date, datetime.min.time())
		now = datetime.combine(datetime.now(), datetime.min.time())
		return (end - now).days
	class Meta:
		verbose_name_plural = "Goals"

class Tasks(models.Model):
	tag = models.CharField(max_length=100, default='tasks', blank=False)
	complete = models.BooleanField(default=False, blank=False)
	body = MarkdownxField()
	end_date = models.DateField(default=timezone.now)
	def time_left(self):
		end = datetime.combine(self.end_date, datetime.min.time())
		now = datetime.combine(datetime.now(), datetime.min.time())
		return (end - now).days
	def formatted_markdown(self):
		return markdownify(self.body)
	class Meta:
		verbose_name_plural = "Tasks"

top_stellar/app_notes/forms.py
from django import forms
from .models import Notes, Soar, Goals, Tasks

class NotesForm(forms.ModelForm):
	class Meta:
		model = Notes
		fields = ['title', 'genre', 'tag', 'body', 'date']

class SoarForm(forms.ModelForm):
    class Meta:
        model = Soar
        fields = ['date', 'genre', 'tag', 'situation', 'obstacle', 'action', 'result']

class GoalsForm(forms.ModelForm):
	class Meta:
		model = Goals
		fields = ['tag', 'complete', 'body', 'end_date']

class TasksForm(forms.ModelForm):
	class Meta:
		model = Tasks
		fields = ['tag', 'complete', 'body', 'end_date']

top_stellar/app_notes/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, TemplateView
from .models import Notes, Soar, Goals, Tasks
from .filters import NotesFilter, SoarFilter, GoalsFilter, TasksFilter
from .forms import NotesForm, SoarForm, GoalsForm, TasksForm
from django_filters.views import FilterView
import app_notes.processing as proc
from django.urls import reverse_lazy

#--------------------------------------------------------------------------------

class HomeListView(ListView):
	template_name = 'app_notes/app_notes.html'
	model = Notes

	def get_queryset(self):
		return Notes.objects.order_by('-date')

	def get_context_data(self, **kwargs):
		t_x = proc.return_top_tags('notes', 'tag', False)
		t_y = proc.return_num_occur('notes', t_x, 'tag')

		g_x = proc.return_top_tags('notes', 'genre', False)
		g_y = proc.return_num_occur('notes', g_x, 'genre')

		st_x = proc.return_top_tags('soar', 'tag', False)
		st_y = proc.return_num_occur('soar', st_x, 'tag')

		sg_x = proc.return_top_tags('soar', 'genre', False)
		sg_y = proc.return_num_occur('soar', sg_x, 'genre')

		context = super().get_context_data(**kwargs)

		context['tags_list'] = t_x
		context['genres_list'] = g_x

		context['incomplete_goals'] = Goals.objects.filter(complete=False)
		context['incomplete_tasks'] = Tasks.objects.filter(complete=False)

		context['tag_data'] = zip(t_x, t_y)
		context['genre_data'] = zip(g_x, g_y)

		context['st_data'] = zip(st_x, st_y)
		context['sg_data'] = zip(sg_x, sg_y)
		
		return context

#--------------------------------------------------------------------------------

class HomeTagsListView(ListView):
	template_name = 'app_notes/app_notes_tag_list.html'
	model = Notes
	paginate_by = 10

	def get_queryset(self):
		return Notes.objects.filter(tag__icontains=self.kwargs['notes_tag']).order_by('-date')

#--------------------------------------------------------------------------------

class HomeGenreListView(ListView):
	template_name = 'app_notes/app_notes_genre_list.html'
	model = Notes
	paginate_by = 10
	def get_queryset(self):
		return Notes.objects.filter(genre__icontains=self.kwargs['notes_genre']).order_by('-date')

#--------------------------------------------------------------------------------

class HomeSoarGenreListView(ListView):
	template_name = 'app_notes/app_soar_genre_list.html'
	model = Soar
	paginate_by = 10
	def get_queryset(self):
		return Soar.objects.filter(genre__icontains=self.kwargs['soar_genre']).order_by('-date')

#--------------------------------------------------------------------------------

class HomeSoarTagsListView(ListView):
	template_name = 'app_notes/app_soar_tag_list.html'
	model = Soar
	paginate_by = 10

	def get_queryset(self):
		return Soar.objects.filter(tag__icontains=self.kwargs['soar_tag']).order_by('-date')

#--------------------------------------------------------------------------------

class FilterListView(ListView):
	filterset_class = None
	ordering = None;

	def get_queryset(self):
		queryset = super().get_queryset().order_by(self.ordering)
		self.filterset = self.filterset_class(self.request.GET, queryset=queryset)
		return self.filterset.qs.distinct()

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['filter'] = self.filterset
		return context



class SearchListView(FilterListView):
	model = Notes
	filterset_class = NotesFilter
	template_name = 'app_notes/app_notes_search.html'
	ordering = '-date'

class SoarSearchListView(FilterListView):
	model = Soar
	filterset_class = SoarFilter
	template_name = 'app_notes/soar_search.html'
	ordering = '-date'

class GoalsSearchListView(FilterListView):
	model = Goals
	filterset_class = GoalsFilter
	template_name = 'app_notes/goals_search.html'
	ordering = '-end_date'

class TasksSearchListView(FilterListView):
	model = Tasks
	filterset_class = TasksFilter
	template_name = 'app_notes/tasks_search.html'
	ordering = '-end_date'

#--------------------------------------------------------------------------------

class NotesCreateView(CreateView):
	template_name = 'app_notes/app_notes_create.html'
	form_class = NotesForm
	model = Notes
	success_url = reverse_lazy('app_notes:homelist')

#--------------------------------------------------------------------------------

class SoarCreateView(CreateView):
	template_name = 'app_notes/app_soar_create.html'
	form_class = SoarForm
	model = Soar
	success_url = reverse_lazy('app_notes:homelist')

#--------------------------------------------------------------------------------

class GoalsCreateView(CreateView):
	template_name = 'app_notes/goals.html'
	form_class = GoalsForm
	model = Goals
	success_url = reverse_lazy('app_notes:homelist')

#--------------------------------------------------------------------------------

class TasksCreateView(CreateView):
	template_name = 'app_notes/tasks.html'
	form_class = TasksForm
	model = Tasks
	success_url = reverse_lazy('app_notes:homelist')

top_stellar/app_notes/templates/app_notes/app_notes.html
{% extends "pjx_stellar.html" %}
{% load staticfiles %}
{% block content %}
<link rel="stylesheet" href="{% static "css/app_notes.css" %}">
<style type="text/css">
#page1{
background-color: #03fc8c;
border-radius: 10px;
color: #000000;
}
</style>
<div class="row mynotes">
	<div class="col-lg-4">
		<div class="sticky-top">
			<div class="row" id="jscalsec"></div>


			<div class="topstuff">
				<h5><i class="fas fa-sticky-note"></i><b> Top Notes</b></h5>
				<span class="badge badge-secondary">Genre</span>
				<span class="badge badge-primary">Tag</span>
				<hr>
			</div>
			<div class="tagging">
				{% for g_x, g_y in genre_data %}
					<a href="{% url 'app_notes:genrelist' notes_genre=g_x %}">
					<span class="badge badge-pill badge-secondary">{{ g_x }} - {{ g_y }}</span>
					</a>
				{% endfor %}
				{% for t_x, t_y in tag_data %}
					<a href="{% url 'app_notes:taglist' notes_tag=t_x %}">
					<span class="badge badge-pill badge-primary">{{ t_x }} - {{ t_y }}</span>
					</a>
				{% endfor %}
			</div>


			<div class="topstuff">
				<h5><i class="fas fa-star-half-alt"></i><b> Top SOAR</b></h5>
				<span class="badge badge-secondary">Genre</span>
				<span class="badge badge-primary">Tag</span>
				<hr>
			</div>
			<div class="tagging">
				{% for sg_x, sg_y in sg_data %}
					<a href="{% url 'app_notes:sgenrelist' soar_genre=sg_x %}">
					<span class="badge badge-pill badge-secondary">{{ sg_x }} - {{ sg_y }}</span>
					</a>
				{% endfor %}
				{% for st_x, st_y in st_data %}
					<a href="{% url 'app_notes:staglist' soar_tag=st_x %}">
					<span class="badge badge-pill badge-primary">{{ st_x }} - {{ st_y }}</span>
					</a>
				{% endfor %}
			</div>


		</div>
	</div>



<div class="col-lg-8">
<div class="goalssec">
<hr>
<h2>Goals</h2>	
{% for goals in incomplete_goals %}
{% if goals.time_left >= 2 %}
<div class="entry"><p><span class="badge badge-info">{{ goals.time_left }} Days</span>{{ goals.formatted_markdown|safe }}</p></div>
{% elif goals.time_left < 2 and goals.time_left > 0 %}
<div class="entry"><p><span class="badge badge-warning">{{ goals.time_left }} Days</span>{{ goals.formatted_markdown|safe }}</p></div>
{% elif goals.time_left <= 0 %}
<div class="entry"><p><span class="badge badge-danger">{{ goals.time_left }} Days</span>{{ goals.formatted_markdown|safe }}</p></div>
{% endif %}
{% empty %}
<p>No Goals</p>
{% endfor %}
<br>
</div>
<div class="taskssec">
<hr>
<h2>Tasks</h2>
{% for tasks in incomplete_tasks %}
{% if tasks.time_left >= 2 %}
<div class="entry"><p><span class="badge badge-info">{{ tasks.time_left }} Days</span>{{ tasks.formatted_markdown|safe }}</p></div>
{% elif tasks.time_left < 2 and tasks.time_left > 0 %}
<div class="entry"><p><span class="badge badge-warning">{{ tasks.time_left }} Days</span>{{ tasks.formatted_markdown|safe }}</p></div>
{% elif tasks.time_left <= 0%}
<div class="entry"><p><span class="badge badge-danger">{{ tasks.time_left }} Days</span>{{ tasks.formatted_markdown|safe }}</p></div>
{% endif %}
{% empty %}
<p>No Tasks</p>
{% endfor %}
<br>
</div>
<div id="notessec"></div>
</div>
</div>
<script type="text/javascript">
	var opt = {weekday: "long", month: 'long', day: 'numeric', year: 'numeric'};
	var today = new Date();
	var notes = [
		{% for note in notes_list %}
			{
				date: "{{ note.date|date:"d/m/Y" }}",
				text: "{{ note.formatted_markdown|escapejs }}",
				title: "{{ note.title }}",
				genre: "{{ note.genre }}",
				tag: "{{ note.tag }}"
			},
		{% endfor %}
	];
</script>
<script type="text/javascript">
	var notesCalendar = jsCalendar.new("#jscalsec", "{% now "d/m/Y" %}", {
		navigator : true,
		navigatorPosition : "right",
		zeroFill : false,
		monthFormat : "month YYYY",
		dayFormat : "DDD",
		language : "en"
	});
	var notesDisplay = document.getElementById("notessec");
	function showNote(date,ddate) {
		var buffer = [];
		var title_buffer = [];
		var genre_buffer = [];
		var tag_buffer = [];

		for ( var i = 0; i < notes.length; i++){
			if(date == notes[i].date){
				buffer.push(notes[i].text);
				title_buffer.push(notes[i].title);
				genre_buffer.push(notes[i].genre);
				tag_buffer.push(notes[i].tag);
			}
		}

		notesDisplay.innerHTML = '';

		var notessection = document.createElement('h2');
		notessection.className = "thenotessection";
		notessection.innerHTML = 'Notes';
		notesDisplay.appendChild(document.createElement("hr"));
		notesDisplay.appendChild(notessection);
		var timestamp = document.createElement('h4');
		timestamp.className = "timestamp";
		timestamp.innerHTML = ddate;
		notesDisplay.appendChild(timestamp);
		notesDisplay.appendChild(document.createElement("br"));
		notesDisplay.appendChild(document.createElement("br"));

		var div;
		var h4_n_title;
		var s_genre;
		var a_genre;
		var s_tag;
		var a_tag;
		var tmp_tag;
		var tmp_genre;

		for (var i = 0; i < buffer.length; i++){

			tmp_tag = tag_buffer[i];
			tmp_genre = genre_buffer[i];

			// the title
			h4_n_title = document.createElement('h4');
			h4_n_title.className = "thetitle";
			h4_n_title.innerHTML = title_buffer[i];

			// the genre
			s_genre = document.createElement('span');
			s_genre.className = "badge badge-pill badge-secondary";
			s_genre.innerHTML = genre_buffer[i];
			a_genre = document.createElement('a');
			a_genre.className = "ngenre";
			a_genre.href = "{% url 'app_notes:genrelist' notes_genre=12345 %}".replace(/12345/, tmp_genre.toString());
			a_genre.appendChild(s_genre);

			// the tag
			s_tag = document.createElement('span');
			s_tag.className = "badge badge-pill badge-primary";
			s_tag.innerHTML = tag_buffer[i];
			a_tag = document.createElement('a');
			a_tag.className = "ntag";
			a_tag.href = "{% url 'app_notes:taglist' notes_tag=12345 %}".replace(/12345/, tmp_tag.toString());
			a_tag.appendChild(s_tag);

			// header section
			hdr = document.createElement('div');
			hdr.className = "notes_hdr";
			hdr.appendChild(h4_n_title);
			hdr.appendChild(a_genre);
			hdr.appendChild(a_tag);

			// the body
			div = document.createElement('div');
			div.className = 'note';
			div.innerHTML = buffer[i];

			// append
			notesDisplay.appendChild(hdr);
			notesDisplay.appendChild(div);
			notesDisplay.appendChild(document.createElement("hr"));
			notesDisplay.appendChild(document.createElement("br"));

		}
	};

	showNote("{% now "d/m/Y" %}", today.toLocaleDateString("en-US", opt));
	notesCalendar.onDateClick(function(event, date){
		showNote(	jsCalendar.tools.dateToString(date, "DD/MM/YYYY"),
					jsCalendar.tools.dateToString(date, "day, month DD, YYYY"));
	});
	for (var i = 0; i < notes.length; i++) {
		notesCalendar.select(notes[i].date);	
	}
</script>

{% endblock content %}

top_stellar/app_notes/templates/app_notes/app_notes_genre_list.html
{% extends "pjx_stellar.html" %}
{% load staticfiles %}
{% block content %}

<link rel="stylesheet" href="{% static "css/app_notes_genre_list.css" %}">
<style type="text/css">
	#page1{
		background-color: #03fc8c;
		border-radius: 10px;
		color: #000000;
	}
</style>
<div class="col app_notes_genre_list">

{% for notes in notes_list %}
<h2 class="font-weight-bold">{{ notes.title }}</h2>
<h4>{{ notes.date|date:"l, F d, Y" }}</h4>
<div class="app_notes_tag_badges">
<span class="badge badge-primary">{{ notes.tag }}</span>
</div>
<p>{{ notes.formatted_markdown|safe }}</p>
<hr>
<br>
{% endfor %}

<div class="row justify-content-center paginationlist">
{% if is_paginated %}
<ul class="pagination text-center">
<div class="backtick">
{% if page_obj.has_previous %}
<li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
{% else %}
<li class="disabled"><span>&laquo;</span></li>
{% endif %}
{% for i in paginator.page_range %}
</div>
<div class="pagenumbers">
{% if page_obj.number == i %}
<li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
{% else %}
<li class="nonactive"><a href="?page={{ i }}">{{ i }}</a></li>
{% endif %}
</div>
<div class="forwardtick">
{% endfor %}
{% if page_obj.has_next %}
<li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
{% else %}
<li class="disabled"><span>&raquo;</span></li>
{% endif %}
</div>
</ul>
{% endif %}
</div>

</div>
{% endblock %}

top_stellar/app_notes/templates/app_notes/app_notes_tag_list.html
{% extends "pjx_stellar.html" %}
{% load staticfiles %}
{% block content %}
<link rel="stylesheet" href="{% static "css/app_notes_tag_list.css" %}">
<style type="text/css">
#page1{
background-color: #03fc8c;
border-radius: 10px;
color: #000000;
}
</style>
<div class="col app_notes_tag_list">
{% for notes in notes_list %}
<h2 class="font-weight-bold">{{ notes.title }}</h2>
<h4>{{ notes.date|date:"l, F d, Y" }}</h4>
<div class="app_notes_genre_badges">
<span class="badge badge-secondary">{{ notes.genre }}</span>
</div>
<p>{{ notes.formatted_markdown|safe }}</p>
<hr>
<br>
{% endfor %}
<div class="row justify-content-center paginationlist">
{% if is_paginated %}
<ul class="pagination text-center">
<div class="backtick">
{% if page_obj.has_previous %}
<li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
{% else %}
<li class="disabled"><span>&laquo;</span></li>
{% endif %}
{% for i in paginator.page_range %}
</div>
<div class="pagenumbers">
{% if page_obj.number == i %}
<li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
{% else %}
<li class="nonactive"><a href="?page={{ i }}">{{ i }}</a></li>
{% endif %}
</div>
<div class="forwardtick">
{% endfor %}
{% if page_obj.has_next %}
<li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
{% else %}
<li class="disabled"><span>&raquo;</span></li>
{% endif %}
</div>
</ul>
{% endif %}
</div>
</div>
{% endblock %}

top_stellar/app_notes/templates/app_notes/app_soar_genre_list.html
{% extends "pjx_stellar.html" %}
{% load staticfiles %}
{% block content %}

<link rel="stylesheet" href="{% static "css/app_soar_genre_list.css" %}">
<style type="text/css">
    #page1{
        background-color: #03fc8c;
        border-radius: 10px;
        color: #000000;
    }
</style>
<div class="col app_soar_genre_list">

{% for soar in soar_list %}
<h2><b>{{ soar.date|date:"l, F d, Y" }}</b></h2>
<div class="app_soar_tag_badges">
<span class="badge badge-primary">{{ soar.tag }}</span>
</div>
<h4><b>Situation</b></h4>
<p>{{ soar.s_formatted_markdown|safe }}</p>
<h4><b>Obstacles</b></h4>
<p>{{ soar.o_formatted_markdown|safe }}</p>
<h4><b>Actions</b></h4>
<p>{{ soar.a_formatted_markdown|safe }}</p>
<h4><b>Results</b></h4>
<p>{{ soar.r_formatted_markdown|safe }}</p>
<hr>
<br>
{% endfor %}

<div class="row justify-content-center paginationlist">
{% if is_paginated %}
<ul class="pagination text-center">
<div class="backtick">
{% if page_obj.has_previous %}
<li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
{% else %}
<li class="disabled"><span>&laquo;</span></li>
{% endif %}
{% for i in paginator.page_range %}
</div>
<div class="pagenumbers">
{% if page_obj.number == i %}
<li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
{% else %}
<li class="nonactive"><a href="?page={{ i }}">{{ i }}</a></li>
{% endif %}
</div>
<div class="forwardtick">
{% endfor %}
{% if page_obj.has_next %}
<li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
{% else %}
<li class="disabled"><span>&raquo;</span></li>
{% endif %}
</div>
</ul>
{% endif %}
</div>

</div>
{% endblock %}

top_stellar/app_notes/templates/app_notes/app_soar_tag_list.html
{% extends "pjx_stellar.html" %}
{% load staticfiles %}
{% block content %}
<link rel="stylesheet" href="{% static "css/app_soar_tag_list.css" %}">
<style type="text/css">
#page1{
background-color: #03fc8c;
border-radius: 10px;
color: #000000;
}
</style>
<div class="col app_soar_tag_list">
{% for soar in soar_list %}
<h2><b>{{ soar.date|date:"l, F d, Y" }}</b></h2>
<div class="app_soar_genre_badges">
<span class="badge badge-secondary">{{ soar.genre }}</span>
</div>
<h4><b>Situation</b></h4>
<p>{{ soar.s_formatted_markdown|safe }}</p>
<h4><b>Obstacles</b></h4>
<p>{{ soar.o_formatted_markdown|safe }}</p>
<h4><b>Actions</b></h4>
<p>{{ soar.a_formatted_markdown|safe }}</p>
<h4><b>Results</b></h4>
<p>{{ soar.r_formatted_markdown|safe }}</p>
<hr>
<br>
{% endfor %}
<div class="row justify-content-center paginationlist">
{% if is_paginated %}
<ul class="pagination text-center">
<div class="backtick">
{% if page_obj.has_previous %}
<li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
{% else %}
<li class="disabled"><span>&laquo;</span></li>
{% endif %}
{% for i in paginator.page_range %}
</div>
<div class="pagenumbers">
{% if page_obj.number == i %}
<li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
{% else %}
<li class="nonactive"><a href="?page={{ i }}">{{ i }}</a></li>
{% endif %}
</div>
<div class="forwardtick">
{% endfor %}
{% if page_obj.has_next %}
<li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
{% else %}
<li class="disabled"><span>&raquo;</span></li>
{% endif %}
</div>
</ul>
{% endif %}
</div>
</div>
{% endblock %}

top_stellar/app_notes/templates/app_notes/goals.html
{% extends "pjx_stellar.html" %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block content %}
<link rel="stylesheet" href="{% static "css/app_notes_create.css" %}">
<style type="text/css">
#page4{
background-color: #03fc8c;
border-radius: 10px;
color: #000000;
}
#create{
background-color: #03fc8c;
border-radius: 10px;
color: #000000;
}
</style>
<div class="col app_notes_create">
<h1 class="text-center"><b>Goals</b></h1>
<br>
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
<div class="card bg-light">
<div class="card-body">
<div class="row">
<div class="form-group col-md-4">
{{ form.end_date.label_tag }}
{% render_field form.end_date class="form-control" %}
</div>
<div class="form-group col-md-4">
{{ form.tag.label_tag }}
{% render_field form.tag class="form-control" %}
</div>
</div>
<div>
{{ form.body.label_tag }}
{% render_field form.body class="form-control" %}
</div>
<br>
<button type="submit" class="btn btn-primary">Create</button>
</div>
</div>
</form>
{{ form.media }}
</div>
{% endblock content %}